### ISSUE TITLE
FPGA LVDS/EEM

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Fastino#16]
* The B side of a LVDS input is the positive one (https://github.com/sinara-hw/Humpback/issues/9)
* We are not completely following the ice40 recommendation for LVDS output resistor network. They recommend 150/140 while we have 140/100 (the LVDS input recommendation) which gives less differential swing (when used as an output). Also the IDC impedance is not 100 but [higher](https://github.com/sinara-hw/Fastino/issues/15#issuecomment-533607171). Maybe 150/140 is actually better in our case, even for LVDS inputs? Or is that too risky? @gkasprow 
* Also use the left bank (2.5V) for LEDs, switches, hw_rev.

**Comment by gkasprow** [comment]
I did such termination on purpose.
The datasheet recommends such values for output only.
When we switch it to input mode, it is terminated with 140Ohm instead of 100R.
That's why I used 100R and lowered the other resistors.
Anyway, with 2.5V we still have 650mV pp. We can make it better by changing 100R to 120R which fits better the cable impedance.

**Comment by jordens** [comment]
Yes. I know why you did that. But it leads to a low output impedance. And the datasheet does document the recommended input impedance/network. 120 Rp is fine with me. Still seems a bit low compared to the IDC cable.
