### ISSUE TITLE
Review V1.1

### ISSUE THREAD

**Issue by pathfinder49** [sinara-hw/Fastino#72]
Review chasnges for V1.1 from [this PR](https://github.com/sinara-hw/Fastino/pull/71).

Specific changes requiring attention:

- [x] DAC-SPI signal integrity
- [x] DAC-SPI series termination
- [x] DAC-SPI parallel termination (DNP)
- [x] P3V3_MP
- [x] En_AFE_PWR pull down
- [x] i2c dependencies
- [x] IC3 grounding
- [x] P/N12V0A capacitors
- [x] DAC channel layout
- [x] component clearances

**Comment by gkasprow** [comment]
- [ ] I would connect pin 8 of IC3 to GND instead of pin 9. It's a subtle difference.
- [ ] I wouldn't pour the GND on the top and bottom layers. There is a subtle difference - it's easier to control how circuits are connected to GND. With copper pour, one can easily create parasitic GND connections between neighboring circuits. This also makes the crosstalk lower. Take into account that vias have inductances and resistances. 
- termination for 2cm traces do not make much sense but let's treat it as a lowpass filter and we want to have identical circuits for all channels
- [ ] C106_x should have a dedicated via to GND. Now it shares with power supply caps which will affect the PSRR
- use tented vias. The only exception is vias in the pad where it must be left open on both sides to not create acid pockets.

**Comment by gkasprow** [comment]
- [ ] I would supply the IC6 and JP1 from P3V3. The IC17 is used to disconnect the I2C bridge from the P3V3 power domain.  When P3V3 is absent, the FPGA will pull all SPI lines to 0.7V.

**Comment by gkasprow** [comment]
- [ ] the supply of the DAC is not optimal. 
![obraz](https://user-images.githubusercontent.com/4325054/78195704-a456a880-7480-11ea-95c1-de5d2e6df9e3.png)
The trace should follow the route: source -> inductor/resistor -> bulk cap -> ceramic cap -> pin
The critical is low impedance of the ceramic cap to GND. In this case the path from this capacitor goes to the neighboring channel.  Now the caps are far away from the IC. The original design did not have such problem
![obraz](https://user-images.githubusercontent.com/4325054/78195948-41194600-7481-11ea-954d-bf119b1d70b3.png)
This can be  improved, for example
![obraz](https://user-images.githubusercontent.com/4325054/78196196-ecc29600-7481-11ea-9336-f798b6a88bf3.png)

**Comment by gkasprow** [comment]
- [ ] reference decoupling is critical. Now the decoupling capacitor is connected between the REF pin and GND of neighboring channels. I placed the decoupling cap between REF and GND on purpose
- [ ] reference bulk capacitor shares ground with a decoupling cap.

**Comment by gkasprow** [comment]
Here are a few images from my teaching materials that explain what I meant. They come from random app notes
![obraz](https://user-images.githubusercontent.com/4325054/78196448-b89ba500-7482-11ea-8d89-35c273680508.png)
![obraz](https://user-images.githubusercontent.com/4325054/78196455-bd605900-7482-11ea-935e-0dfc2f558784.png)
![obraz](https://user-images.githubusercontent.com/4325054/78196462-c2250d00-7482-11ea-8943-27deee8932df.png)
![obraz](https://user-images.githubusercontent.com/4325054/78196468-c5b89400-7482-11ea-98f1-537fc0a6e3ff.png)
![obraz](https://user-images.githubusercontent.com/4325054/78196478-cb15de80-7482-11ea-8431-1f93e1172fd7.png)
![obraz](https://user-images.githubusercontent.com/4325054/78196483-d23cec80-7482-11ea-9214-8e0203d3903a.png)

**Comment by gkasprow** [comment]
- [ ] the ceramic caps are too far away from +/-12V pins of the opamps. It is not that important as in case of the DACs.
- [ ] LDAC is too close to high impedance opamp input
![obraz](https://user-images.githubusercontent.com/4325054/78196696-7b83e280-7483-11ea-9c61-14c0fa3cf5b7.png)
this can be fixed in such way
![obraz](https://user-images.githubusercontent.com/4325054/78196790-bede5100-7483-11ea-8c77-f526226a500d.png)

**Comment by gkasprow** [comment]
-[ ] we can get rid of R153 ane make space for correct VREF decoupling

**Comment by gkasprow** [comment]
- [ ] increase the clearance between the traces and copper pour because of massive antennas/resonators that cause additional coupling between tracks
![obraz](https://user-images.githubusercontent.com/4325054/78196973-63f92980-7484-11ea-9ae2-71f57653f81f.png)

**Comment by pathfinder49** [comment]
> I would connect pin 8 of IC3 to GND instead of pin 9. It's a subtle difference.

I went with pin 9 as I tested that configuration. Is there a strong reason to go with pin 8 instead?

> reference decoupling is critical. Now the decoupling capacitor is connected between the REF pin and GND of neighboring channels. I placed the decoupling cap between REF and GND on purpose

Are you refering to the top and bottom GND polygon here?

**Comment by pathfinder49** [comment]
@gkasprow I've pushed an updates addressing your points except the IC3 pin. Could you please take another look?

**Comment by pathfinder49** [comment]
@gkasprow Do you know when you'll have a chance to look at this?

**Comment by gkasprow** [comment]
@pathfinder49 next time pls write an email directly to me.

**Comment by gkasprow** [comment]
@pathfinder49 where is the PCB? I cloned your repo and there is the old version..

**Comment by pathfinder49** [comment]
It's on the branch "fixes" (apologies for the poor naming). https://github.com/pathfinder49/Fastino/tree/fixes

**Comment by gkasprow** [comment]
I think it is good enough. Every project can be done better, but here the main goal is high channel isolation. Let's produce it;

**Comment by gkasprow** [comment]
I changed the rev_ID from 1 to 2

**Comment by pathfinder49** [comment]
@gkasprow If you merge PRs through the webinterface, the linked issues can be closed automatically :wink:
